import 'package:flutter/material.dart';
import '/backend/backend.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'flutter_flow/flutter_flow_util.dart';

class FFAppState extends ChangeNotifier {
  static FFAppState _instance = FFAppState._internal();

  factory FFAppState() {
    return _instance;
  }

  FFAppState._internal();

  static void reset() {
    _instance = FFAppState._internal();
  }

  Future initializePersistedState() async {
    prefs = await SharedPreferences.getInstance();
    _safeInit(() {
      _userRoutine = prefs
              .getStringList('ff_userRoutine')
              ?.map((x) {
                try {
                  return RoutineItemStruct.fromSerializableMap(jsonDecode(x));
                } catch (e) {
                  print("Can't decode persisted data type. Error: $e.");
                  return null;
                }
              })
              .withoutNulls
              .toList() ??
          _userRoutine;
    });
    _safeInit(() {
      _reminderTime = prefs.containsKey('ff_reminderTime')
          ? DateTime.fromMillisecondsSinceEpoch(
              prefs.getInt('ff_reminderTime')!)
          : _reminderTime;
    });
  }

  void update(VoidCallback callback) {
    callback();
    notifyListeners();
  }

  late SharedPreferences prefs;

  List<RoutineItemStruct> _userRoutine = [];
  List<RoutineItemStruct> get userRoutine => _userRoutine;
  set userRoutine(List<RoutineItemStruct> value) {
    _userRoutine = value;
    prefs.setStringList(
        'ff_userRoutine', value.map((x) => x.serialize()).toList());
  }

  void addToUserRoutine(RoutineItemStruct value) {
    _userRoutine.add(value);
    prefs.setStringList(
        'ff_userRoutine', _userRoutine.map((x) => x.serialize()).toList());
  }

  void removeFromUserRoutine(RoutineItemStruct value) {
    _userRoutine.remove(value);
    prefs.setStringList(
        'ff_userRoutine', _userRoutine.map((x) => x.serialize()).toList());
  }

  void removeAtIndexFromUserRoutine(int index) {
    _userRoutine.removeAt(index);
    prefs.setStringList(
        'ff_userRoutine', _userRoutine.map((x) => x.serialize()).toList());
  }

  void updateUserRoutineAtIndex(
    int index,
    RoutineItemStruct Function(RoutineItemStruct) updateFn,
  ) {
    _userRoutine[index] = updateFn(_userRoutine[index]);
    prefs.setStringList(
        'ff_userRoutine', _userRoutine.map((x) => x.serialize()).toList());
  }

  void insertAtIndexInUserRoutine(int index, RoutineItemStruct value) {
    _userRoutine.insert(index, value);
    prefs.setStringList(
        'ff_userRoutine', _userRoutine.map((x) => x.serialize()).toList());
  }

  List<dynamic> _HipResults = [
    jsonDecode(
        '{"Title":"INTERNAL HIP ROTATION LIFT","Directions":"This is an internal hip rotation mobility and stability exercise. Start by lying down on your back with a yoga block or foam roller between your knees and heels planted on a bench. Squeeze the yoga block and raise the pelvis one inch off the ground. Hold the raised position for up to 5 seconds. Come back down to a rested position to complete the first repetition. Then rotate one leg out by 5-10 degrees and complete another hip lift. Repeat until 45 degrees of hip rotation is achieved or until the maximum range you can tolerate is achieved for the day.","Muscles Involved":["Glutes","Gluteus Maximus (Hip Extension)","Gluteus Medius Anterior Fibers (Hip Internal Rotation)","Gluteus Minimus (Hip Internal Rotation)","Hamstrings","Tensor Fascia Latae (TFL)","Adductors","Adductor Longus","Adductor Magnus","Adductor Brevis","Pectineus"],"Related Conditions":["Hip Impingement","Internal Snapping Hip Syndrome","External Snapping Hip Syndrome","Groin Strain","Hip Spine Syndrome","Mechanical Low Back Pain","Lower Kinetic Pain Syndrome","Hip Bursitis","ITB Syndrome","Sacroiliac Joint Syndrome"],"Video Link":"https://www.youtube.com/embed/YylAVqnt2Mw?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/61ccb01a57336a5a31ba0526/1687362339845/Internal%2BRotation%2BHip%2BLift.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/internal-rotation-hip-lift","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"KNEELING HALF MOON POSE","Directions":"The kneeling half moon pose is a yoga inspired exercise that is a regressed version of the convention HIP AIRPLANE exercise. Do this closed chain hip abduction exercise to engage your hip muscles and to improve hip stability. Start on your hands and knees and slowly lift up one side’s arm and leg up while rotating upwards with the torso. Extend the raised leg out through the heel and reach towards the ceiling with your arm. Keep the spine neutral by keeping the shoulders squared with your hips.","Muscles Involved":["Glutes","gluteus medius","gluteus maximus","piriformis","Core","external oblique","internal oblique","transversus abdominis","quadratus lumborum"],"Related Conditions":["Glute Amnesia","Sacroiliac Joint Syndrome","Low Back Pain","Hip Spine Syndrome","hip bursitis","greater trochanteric pain syndrome","gluteus maximus tendinitis","gluteus medius tendinitis"],"Video Link":"https:https://www.youtube.com/embed/rNPIXyPJC58?feature=oembed","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/4ab7c748-4dfd-4263-9c04-623a57daebd2/Foam+Roller+Single+Leg+Bridge.jpg","URL":"https://www.rehabhero.ca/exercise/kneeling-half-moon-pose","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"BANDED SPIDERMAN STRETCH","Directions":"This banded hip joint mobilization targets your hip capsule. The hip capsule surrounds the femoralacetabular joint and can become irritated in conditions like Hip Impingement. For this exercise use a heavy strength band (100 lbs resistance shown in the video) and hold the position for 1-2 minutes. This exercise can also be done on the floor however elevating the foot on a bench does make this hip mobility exercise much easier.","Muscles Involved":["Femoralacetabular Joint","Hip Capsule"],"Related Conditions":["Functional Hip Impingement","Femoral Acetabular Impingement","CAM Deformity","Pincer Grip Deformity","Glute Amnesia","Anterior Femoral Glide Syndrome","Hip Labral Tear","Greater Trochanteric Bursitis","External Snapping Hip Syndrome"],"Video Link":"https://www.youtube.com/embed/3lmIT0azKMg?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/de78522a-e714-4c36-a3f0-91ae83a750e5/QL+Glute+stretch.jpg","URL":"https://www.rehabhero.ca/exercise/banded-spiderman-stretch","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"HIP DROPS","Directions":"This is a hip stretch exercise that works on stretching out your hip abductors. Alternate side to side as a warm up to loosen up your hips, or this can be used as a cool down to promote recovery.","Muscles Involved":["Gluteus Maximus","Gluteus Medius","Lateral Line"],"Related Conditions":["ITB Syndrome","Hip Bursitis","Greater Trochanteric Pain Syndrome","External Snapping Hip Syndrome","Glute Amnesia","Lower Kinetic Pain Syndrome"],"Video Link":"https://www.youtube.com/embed/4OToVbflmBg?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/5fd27b8f2a6b2d38d0231535/1687360464464/Hip%2BDrops.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/hip-drops","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"SIDE LUNGE HIP ROTATIONS","Directions":"This is a hip mobility exercise that challenges your hip in external rotation and abduction.","Muscles Involved":["Hip Adductors","Hamstrings"],"Related Conditions":["Groin Strain","Hamstring Tendinopathy"],"Video Link":"https://www.youtube.com/embed/Mdy0iSAo994?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/de78522a-e714-4c36-a3f0-91ae83a750e5/QL+Glute+stretch.jpg","URL":"https://www.rehabhero.ca/exercise/side-lunge-hip-rotations","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"TAILOR’S STRETCH","Directions":"This is a seated easy-to-do hip stretch that can help to loosen you up.","Muscles Involved":["Gluteus Maximus","Piriformis"],"Related Conditions":["Low Back Pain","Piriformis Syndrome"],"Video Link":"https://www.youtube.com/embed/ziZXGFLmSzs?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/5fd2a4b9f800b4559815c2ed/1687725848427/Tailor%2527s%2BStretch.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/tailors-stretch","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"RUNNER’S STANCE HOLDS","Directions":"This is an isometric strengthening exercise that aims to increase leg stability for running. This is a sport specific exercise for sports such as soccer, sprinting, jogging, and marathon running.","Muscles Involved":["Glutes (Gluteus Maximus, Minimus, Medius)","Hip Flexors (Iliopsoas)","Hamstrings","Quadriceps"],"Related Conditions":["Sport Specific Training","Strengthening and Conditioning","Sacroiliac Joint Syndrome"],"Video Link":"https://www.youtube.com/embed/d3i8dPvSED0?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/5fe9020339fc07786eaf2d96/1687703148303/Runners%2BStance%2BHolds.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/runners-stance-holds","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"BRETTZEL STRETCH","Directions":"This exercise is for thoracic and lumbar spine mobility as well as hip flexibility. Start by lying down on your back and flex one hip and knee to 90 degrees. Grab that knee with your opposite hand and pull it across the body and towards the floor. Use your other hand to grab your foot or ankle of the other leg and keep it pinned to the floor. Hold this position without allow your shoulders to come off of the ground. Take 3-5 deep breathes and switch sides.","Muscles Involved":["Lumbar Spine","Thoracic Spine","Glutes","Obliques","Latissimus Dorsi","Quadratus Lumborum","Multifidus","Quadriceps","Iliopsoas"],"Related Conditions":["Chronic Low Back Pain","Thoracolumbar Syndrome","Hip Spine Syndrome","Lower Cross Syndrome","Sacroiliac Joint Syndrome","Lumbar Facet Syndrome"],"Video Link":"https://www.youtube.com/embed/c1Fj6--hWbo?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/603e4448be32591be49e5c37/1687359847902/Brettzel%2BStretch.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/brettzel-stretch","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"SUPINE CLAMSHELL","Directions":"This is a hip abductor and external rotation strengthening exercise. Wrap a band around your knees (either just below or above the joint line) and lie down on your back. Bench your knees to 90 degrees and keep your feet and knees together. Proceed to resisted against the band’s pull by spreading the knees as far as possible while keeping the heels planted.","Muscles Involved":["Gluteus Maximus","Gluteus Medius"],"Related Conditions":["Hip Bursitis","External Snapping Hip Syndrome","Hip Spine Syndrome","Squat Warm Up","Lower Kinetic Pain Syndrome","Glute Amnesia","Knocked Knees / Genu Valgum","Piriformis Syndrome"],"Video Link":"https://www.youtube.com/embed/LeOfZeSWfkM?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/de78522a-e714-4c36-a3f0-91ae83a750e5/QL+Glute+stretch.jpg","URL":"https://www.rehabhero.ca/exercise/supine-clamshells","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"ELEVATED MOUNTAIN CLIMBER SLIDER","Directions":"This is core and hip flexor strengthening exercise that uses slider disks. Start in a high plank position with your hands elevated by a bench, edge of a sofa or parallettes. Keep the spine neutral as you slide you legs into hip flexion and extension. Keep alternating legs.","Muscles Involved":["Core","Hip Flexors"],"Related Conditions":["Chronic Low Back Pain","Hip Spine Syndrome","Hip Impingement","Snapping Hip Syndrome","Iliopsoas Tendinopathy"],"Video Link":"https://www.youtube.com/embed/7A0fLIdc1RE?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/604140b00771d01c0fe959f7/1646781286425/Mountain%2BClimber%2BSliders.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/mountain-climber-sliders","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"HIGH BRIDGE HIP MARCH","Directions":"This exercise is used to strengthen the hip flexors in one leg while strengthen the hip extensors in the other leg and can be used as part of a running strength program. Bridge your body up with your hands on an elevated surface like a bench or edge of a sofa. Loop a miniband around both feet and extend both hips to neutral. Raise one knee to 90 degrees hip flexion and hold for up to 5 seconds and alternate sides.","Muscles Involved":["Gluteus Maximus","Hamstrings","Iliopsoas (Hip Flexors)","Core"],"Related Conditions":["Internal Snapping Hip Syndrome","Iliopsoas Tendinopathy","Squat Warm Up","Hip Spine Syndrome","Hip Impingement"],"Video Link":"https://www.youtube.com/embed/Ld3jN0CFwLk?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/de78522a-e714-4c36-a3f0-91ae83a750e5/QL+Glute+stretch.jpg","URL":"https://www.rehabhero.ca/exercise/high-bridge-hip-march","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"RNT ADDUCTOR DEADLIFTS","Directions":"This is a neuromuscular reactive training technique to recruit the hip adductors as hip and knee stabilizers during the deadlift exercise. Loop a band around one knee and around a stable pole or squat rack frame. The band can be looped above or below the knee joint based on personal preferences. Complete a deadlift while resisting the band’s pull.","Muscles Involved":["Hip Adductors","Hamstrings","Gluteus Maximus","Erector Spinae","Core"],"Related Conditions":["Deadlift Related Low Back Pain","Sacroiliac Joint Syndrome","Pes Anserine Bursitis","Groin Strain"],"Video Link":"https://www.youtube.com/embed/nUdrRM04oOs?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/6054e2a26f72c166dbf7c934/1687710271392/RNT%2BAdductor%2BDeadlift.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/rnt-adductor-deadlift","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"90/90 HIP THRUST","Directions":"This is a hip mobility exercise that targets the front leg in internal rotation and the back leg in external rotation and transitions them through hip extension to a neutral flexion position. It is a modified and advanced version of the 90/90 HIP SWITCH exercise. Start by sitting down on the floor with your legs bent to 90 degrees a the knees and feet placed wider than shoulder width apart. Proceed to internally rotate the front leg and externally rotate the back leg until both knees reach the floor. From here lift the pelvis off the ground to engage the hip muscles. Reverse the motion and repeat for the opposite side.","Muscles Involved":["Glutes (Gluteus Maximus, Medius, Minimus)","TFL (Tensor Fascia Latae)"],"Related Conditions":["Squat Warm Up","External Snapping Hip Syndrome","Greater Trochanter Pain Syndrome / Bursitis","Gluteal Tendinopathy","Glute Amnesia","Sacroiliac Joint Syndrome"],"Video Link":"https://www.youtube.com/embed/RvV3HrLXbQk?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/de78522a-e714-4c36-a3f0-91ae83a750e5/QL+Glute+stretch.jpg","URL":"https://www.rehabhero.ca/exercise/9090-hip-thrust","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"BANDED SIDE KICKS / BANDED HIP ABDUCTIONS","Directions":"This is a strengthening exercise for the hip abductors in the frontal plane. Lie down on your side with both knees straight and a mini band looped around your legs just above the ankles. Raise the top leg directly to the side without rotating the pelvis or leg forwards or backwards. Go for maximum range and hold the top position for up to 2 seconds before lowering.","Muscles Involved":["Glutes (Gluteus Maximus, Gluteus Medius, Gluteus Minimus)","Tensor Fascia Latae (TFL)"],"Related Conditions":["Hip Osteoarthritis","Hip Labral Tear","Total Hip Replacement","External Snapping Hip Syndrome","Sacroiliac Joint Syndrome","Greater Trochanteric Pain Syndrome / Bursitis","Glute Amnesia","Pseudo Sciatica","Gluteal Tendinopathy","ITB Syndrome","Knocked Knees / Genu Valgum"],"Video Link":"https://www.youtube.com/embed/ozTqEt75RR4?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/de78522a-e714-4c36-a3f0-91ae83a750e5/QL+Glute+stretch.jpg","URL":"https://www.rehabhero.ca/exercise/banded-side-kicks","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"DOWEL HIP HINGE","Directions":"This is a motor patterning exercise that is used to train hold a neutral spine in hip flexion activities like the SQUAT or DEADLIFT. Place a dowel or broomstick on your back and anchor it again your head, between your shoulder blades, and on your tail bone. Keep a light bend in your knees and hinge forwards at the hips as far as possible without allowing the dowel to come off the three anchor points. Stand straight back up and repeat as required.","Muscles Involved":["Core (Transverse Abdominis)","Hamstrings","Erector Spinae"],"Related Conditions":["Squat Warm Up","Deadlift Warm Up","Mechanical Low Back Pain","Sacroiliac Joint Syndrome","Thoracolumbar Syndrome"],"Video Link":"https://www.youtube.com/embed/0PJfAdtzGSs?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/608ed1562c280c5e2fdb6a8b/1687527309606/Dowel%2BHip%2BHinge.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/dowel-hip-hinge","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"PSOAS SIT UP","Directions":"This is a closed chain hip flexor strengthening exercise. Start by hooking your foot through the loop of a kettlebell handle while lying down on a bench. Hug your other knee to your chest and sit up using your hip flexor.","Muscles Involved":["Iliopsoas (Psoas Major and Iliacus)","Rectus Femoris","Sartorius"],"Related Conditions":["Iliopsoas Tendinitis / Tendinopathy","Hip Impingement","Hip Spine Syndrome","Internal Snapping Hip Syndrome"],"Video Link":"https://www.youtube.com/embed/LDIkAJBmTBQ?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/609829fb49cbdd7840622d9a/1687709490781/Psoas%2BSit%2BUp.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/psoas-sit-up","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"WALKING LUNGES","Directions":"This is a quadriceps strengthening exercise. You may use or not use weights such as dumbbells or kettlebells during this exercise. Lunge forward by planting the lead leg’s foot on the ground in front of you. Lunge downwards by bending the lead leg to 90 degrees hip and knee flexion. Drive your lead leg’s foot into the ground to raise the body up and stride forward straight into your next step with your other leg. Keep the spine neutral and the knee in line with the middle of your foot.","Muscles Involved":["Quadriceps","Gluteus Maximus"],"Related Conditions":["Strength and Conditioning / Strength Training","Patellar Tendinitis / Quadriceps Tendinitis","Quadriceps Strain","Patellofemoral Pain Syndrome","ITB Syndrome","Knee Meniscus Tear","ACL / PCL / MCL / LCL Tear"],"Video Link":"https://www.youtube.com/embed/wPf5b1RxlXA?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/859029da-c82e-4836-aaf0-a865dfcbbcec/step+down+toe+tap.jpg","URL":"https://www.rehabhero.ca/exercise/walking-lunges","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"DOWEL HIP INTERNAL ROTATION","Directions":"This is a hip assisted stretching exercise that targets the hip external rotators in hip flexion. You will require a chair or bench and a dowel or broomstick. Take a seat and wrap your leg around a dowel by place it against the inner heel and outer thigh. Maintain contact and use your hands to drive the hip into end range hip internal rotation. Hold this position for up to 30 seconds or 3-5 breaths and repeat between 3-5 times as needed. Normal internal rotation is roughly 45 degrees. Keep the knee bent to 90 degrees.","Muscles Involved":["Gluteus Medius","Triceps Coxae","Superior Gemellus","Inferior Gemellus","Obturator Internus","Quadratus Femoris"],"Related Conditions":["Hip Impingement","Hip Osteoarthritis","ITB Syndrome","Greater Trochanteric Pain Syndrome","Hip Bursitis"],"Video Link":"https://www.youtube.com/embed/Ya9Aef-mr5Q?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/1637263219191-UNC1HK57E20NATDB7OMI/Couch%252BStretch.jpg","URL":"https://www.rehabhero.ca/exercise/dowel-hip-internal-rotation","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"SUPINE PELVIC TILTS","Directions":"This is a motor control and patterning exercise that aims to give you individual control of your pelvis. The goal of this exercise is to learn how to tilt the pelvis back and forth without using your hips or upper back to compensate for the movement. Lie down on your back with your feet planted on the floor and knees bent to 90 degrees. You may place your hands on your pelvis to help visualize or assist this movement. Tilt the pelvis forwards to arch (extend) the lumbar spine without using your legs. Tilt the pelvis back wards to curl (flex) the lumbar spine.","Muscles Involved":["Sacroiliac Joint","Lumbar Spine","Femoroacetabular Joint"],"Related Conditions":["Anterior Pelvic Tilt","Lower Cross Syndrome","Sacroiliac Joint Syndrome","Lumbar Facet Syndrome","Thoracolumbar Syndrome","Hip Spine Syndrome","Pseudo Sciatica"],"Video Link":"https://www.youtube.com/embed/DqqUIfMuDX4?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/60cde5953838956a5ac55029/1687727727370/Supine%2BPelvic%2BTilt.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/supine-pelvic-tilt","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"FRONT LEG SWING","Directions":"This is a dynamic warm up exercise for the hip and thigh muscles. You may hold onto a stable object with your hands for added balance. Raise one leg off of the ground in front of you and swing it back and forth. Slowly progress to increasing the range of motion as the muscles adapt to the change in length.","Muscles Involved":["Superficial Front Line","Quadriceps","Iliopsoas","Rectus Abdominus","Superficial Back Line","Gastrocnemius","Soleus","Hamstrings","Gluteus Maximus"],"Related Conditions":["Sport Specific Warm Up - Running, Soccer, Tennis, etc"],"Video Link":"https://www.youtube.com/embed/NYn9R3WyKzI?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/6125467dc07eaf53a44c710a/1646597501791/Front%2BLeg%2BSwing.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/front-leg-swing","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"ADDUCTOR SQUEEZE BRIDGE","Directions":"This is a hip adductor strengthening exercise that is used to build knee and hip stability. Place a yoga block or foam roller between the knees and squeeze it with a high amount of effort while laying in crook position (on your back with knees bent). Place your feet about hip distance apart. While maintaining a strong squeeze, lift the pelvis off of the floor while maintaining a neutral spine. Hold for 2 seconds then lower the pelvis back down to the ground.","Muscles Involved":["Hip Adductors","Adductor Magnus","Adductor Longus","Adductor Brevis","Pectineus","Gracilis"],"Related Conditions":["Groin Strain","Hip Adductor Strain","Pes Anserine Bursitis","Knocked Knees / Genu Valgum"],"Video Link":"https://www.youtube.com/embed/VdOpPgavXXU?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/38edee02-4799-4920-bf37-31f1d6309de6/Hamstring+Clock+Stretch.jpg","URL":"https://www.rehabhero.ca/exercise/adductor-squeeze-bridge","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"ADDUCTOR SQUEEZE BRIDGE KICK","Directions":"This is a hip adductor strengthening exercise that is used to build knee and hip stability. Place a yoga block or foam roller between the knees and squeeze it with a high amount of effort while laying in crook position (on your back with knees bent). Place your feet about hip distance apart. While maintaining a strong squeeze, lift the pelvis off of the floor while maintaining a neutral spine. Lift one leg off of the ground by extending the knee and hold for 2 seconds then lower the pelvis back down to the ground.","Muscles Involved":["Hip Adductors","Adductor Magnus","Adductor Longus","Adductor Brevis","Pectineus","Gracilis"],"Related Conditions":["Groin Strain","Hip Adductor Strain","Pes Anserine Bursitis","Knocked Knees / Genu Valgum"],"Video Link":"https://www.youtube.com/embed/iWfM_GC1ogs?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/38edee02-4799-4920-bf37-31f1d6309de6/Hamstring+Clock+Stretch.jpg","URL":"https://www.rehabhero.ca/exercise/adductor-squeeze-bridge-kick","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"BILATERAL INTERNAL ROTATION HIP BRIDGE","Directions":"This is an internal hip rotation mobility and stability exercise. Start by lying down on your back with a yoga block or foam roller between your knees and heels planted on a bench. Squeeze the yoga block and raise the pelvis off the ground by going into full hip extension. Come back down to a rested position to complete the first repetition. Then rotate both legs out by 5-10 degrees and complete another bridge. Repeat until 45 degrees of hip rotation is achieved or until the maximum range you can tolerate is achieved for the day.","Muscles Involved":["Glutes","Gluteus Maximus (Hip Extension)","Gluteus Medius Anterior Fibers (Hip Internal Rotation)","Gluteus Minimus (Hip Internal Rotation)","Hamstrings","Tensor Fascia Latae (TFL)","Adductors","Adductor Longus","Adductor Magnus","Adductor Brevis","Pectineus"],"Related Conditions":["Hip Impingement","Internal Snapping Hip Syndrome","External Snapping Hip Syndrome","Groin Strain","Hip Spine Syndrome","Mechanical Low Back Pain","Lower Kinetic Pain Syndrome","Hip Bursitis","ITB Syndrome","Sacroiliac Joint Syndrome"],"Video Link":"https://www.youtube.com/embed/Wa1nSb7n0e8?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/5cc134c4-b4b8-4cce-b681-dfc3f37f37eb/Reverse+Clamshell.jpg","URL":"https://www.rehabhero.ca/exercise/bilateral-internal-rotation-bridge","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"SINGLE LEG ECCENTRIC HIP BRIDGE | SINGLE LEG ECCENTRIC GLUTE BRIDGE","Directions":"This is a single leg hip extension strengthening exercise. Lie down on your back and bend both knees to 90 degrees. Lift the pelvis off of the ground using both feet then raise the non-target leg off the ground into 90 degrees hip flexion. Keep the target leg’s heel planted and drive it downwards as you lower the pelvis to the ground at a 5-10 second tempo. Keep the spine neutral by bracing the core prior to lifting up the pelvis.","Muscles Involved":["Gluteus Maximus","Hamstrings"],"Related Conditions":["External Snapping Hip Syndrome","Glute Amnesia","Glute Strain","Hamstring Strain","Hip Bursitis","Hip Spine Syndrome","Lower Kinetic Pain Syndrome","Proximal Hamstrings Tendinitis / Hamstrings Tendinopathy / Hamstrings Tendinosis","Sacroiliac Joint Syndrome / SIJ Syndrome","Squat Warm Up","Yoga Butt"],"Video Link":"https://www.youtube.com/embed/v20rAjoX1fQ?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/130dbc59-3c90-48be-91cd-2a7721d097ab/row+lunge.jpg","URL":"https://www.rehabhero.ca/exercise/single-leg-eccentric-bridge","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"ELEVATED PIGEON STRETCH","Directions":"This is a stretch for the front leg’s glutes. Rotate your front thigh so that the knee faces outwards from the body and keep the shin planted on a bench. Have the other leg straight out behind you. Drop the hip towards the ground and support your body with your hands. Keep the spine neutral to isolate the stretch to the hips. Take 3-5 deep breaths or hold for 20-30 seconds and switch sides.","Muscles Involved":["Gluteus Maximus","Piriformis"],"Related Conditions":["Piriformis Syndrome","Hip Spine Syndrome","Low Back Pain","Sacroiliac Joint Syndrome"],"Video Link":"https://www.youtube.com/embed/UrBAdKjH2nE?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/620ff53851b34d30cea2d273/1646590990115/Elevated%2BPigeon%2BStretch.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/elevated-pigeon-stretch","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"ANTERIOR HIP CAPSULAR GLIDE","Directions":"This is a band assisted hip capsule mobilization technique used to target the anterior capsule. Start by anchoring a heavy strength / pullup assist band at hip height while in a tall kneel position. Loop the other end around your target hip then rotate your hip externally. Allow the band to pull your femoral head forwards (do not resisted the band’s pull) to feel a capsular stretch at the front of your hip. You may hold this for up to 30-60 seconds.","Muscles Involved":["Anterior Capsule of the Hip","TFL (Tensor Fascia Latae)","Illiopsoas","Pectineus","Gracilis"],"Related Conditions":["Hip Impingement","Internal Snapping Hip Syndrome","Iliopsoas Tendinopathy","Hip Hypomobility"],"Video Link":"https://www.youtube.com/embed/AaoAcNWGSbE?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/624a2712739cb46a72f3e4bd/1652799659384/Anterior+Hip+Capsule+Glide.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/anterior-hip-capsule-glide","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"ADDUCTOR SQUEEZE WALL SIT","Directions":"This is an isometric stability exercise for the knee extensors and hip adductors. Start by sitting in the air with your back leaned against the wall. Sit so that knees are bent to 90 degrees. Squeeze a foam roller or yoga block between the knees to engage the inner thigh muscles. Hold this position for 10-15 seconds and switch feet positions if needed.","Muscles Involved":["Quadriceps","Hip adductors","Adductor Magnus","Adductor Brevis","Adductor Longus","Gracilis","Pectineus","Quadriceps Tendon","Patellar Tendon"],"Related Conditions":["Patellofemoral pain syndrome","Runner’s knee","Jumper’s knee","Quadriceps tendinopathy / patellar tendinopathy","Quadriceps strain","ACL sprain","Pes anserine bursitis","Groin strain","Hip adductor strain"],"Video Link":"https://www.youtube.com/embed/zxRafspd9HE","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/63acd787de752664067848da/1673622019875/Adductor+Squeeze+Wall+Sit.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/adductor-squeeze-wall-sit","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"CROSSED LEG FORWARD STRETCH","Directions":"This is a stretching exercise for the muscles of the posterior chain and pelvis. Start by sitting crossed legged. Begin to lean forwards leading with your hands. Crawl your hands forwards to deepen the stretch. Hold this position for 20-30 seconds while focusing on relaxing breaths. Return to starting position by walking your hands back towards your body.","Muscles Involved":["Erector Spinae","Quadratus Lumborum","Piriformis","Gluteus Medius","Gluteus Maximus"],"Related Conditions":["Piriformis syndrome","Pelvic floor dysfunction","SIJ syndrome / sacroiliac joint syndrome","Facet joint syndrome","Posterior chain dysfunction"],"Video Link":"https:https://www.youtube.com/embed/575CtRbXA5k?feature=oembed","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/63b743892f908325b121b459/1687356566134/Crosseed+Leg+Forward+Stretch.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/crossed-leg-forward-stretch","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"ROW LUNGE","Directions":"The row lunge exercise is used to strengthen the functional back fascial line. Start by anchoring a band in front of your at the level of your belly button. Grip the other hand with the target arm and start in a lunge position with the front leg begin the opposite leg. Simultaneously being to pull the band through a row motion while going into a single leg stand. Be sure to raise  the same side leg’s knee to hip height. Reverse the motion to complete a repetition.","Muscles Involved":["functional back line","latissimus dorsi","gluteus maximus","rhomboids","quadriceps"],"Related Conditions":["functional back line dysfunction","sacroiliac joint syndrome","lumbar facet syndrome","oblique strain","QL strain","gluteus maximus tendinitis","piriformis syndrome","pseudo sciatica","back strain"],"Video Link":"https:https://www.youtube.com/embed/78PMY0RRg9Q?feature=oembed","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/1627651778183-BR31OXQDYL6RUSA8VJFM/Sumo%2BDeadlift.jpg","URL":"https://www.rehabhero.ca/exercise/row-lunge","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"GOBLET SUMO SQUAT","Directions":"The goblet sumo squat exercise is used to target the muscles of the inner thigh. Start by taking a wide stance with your feet, placing them wider than shoulder distance apart. Hold a kettlebell or dumbbell with your hands at chest level. Begin to squat down while making sure that the knees are aligned with the center of your feet. Squat down until your thighs are parallel with your feet and complete a repetition by extending the hips and knees to return to standing position.","Muscles Involved":["hamstrings","semitendinosus","semimembranosus","hip adductors","adductor magnus","adductor longus","quadriceps","vastus medialis","rectus femoris","glutes","gluteus maximus","gluteus medius"],"Related Conditions":["groin strain","hamstring strain","quadriceps strain","hip impingement","hip bursitis","dynamic hip instability","pes anserine bursitis","hip adductor tendinitis","hamstring tendinitis"],"Video Link":"https:https://www.youtube.com/embed/lZw6v61sNMc?feature=oembed","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/4e925307-6db5-4adb-8339-4d75d5afe674/seated+levator+scapulae+strain.jpg","URL":"https://www.rehabhero.ca/exercise/goblet-sumo-squat","Muscle group":["Hip"]}'),
    jsonDecode(
        '{"Title":"KETTLEBELL SUMO DEADLIFT","Directions":"This is a modified version of CONVENTIONAL DEADLIFT that utilizes a wider stance to bias the movement to increase quadriceps activation. Start with your feet wider than shoulder distance apart and hands gripping on a kettlebell. Your feet may be externally rotated between 15 to 30 degrees. Hinge at the hips and bend the knees to maintain a neutral spine. Be sure to keep the arms close to the body. Keep the core braced and the latissimus dorsi isometrically contracted to increase lumbar stability. Lift the weight up by driving the feet into the ground and extending at the hips and knees. Stand tall through the hips at the top of the movement. Lower the weight by reversing the motion.","Muscles Involved":["Posterior Chain","Erector Spinae","Hamstrings","Functional Backline","Gluteus Maximus","Latissimus Dorsi","Transversus Abdominis","Quadriceps"],"Related Conditions":["Strength Training","Chronic Low Back Pain","Functional Scoliosis","Lower Kinetic Pain Syndrome","Sacroiliac Joint Syndrome","Thoracolumbar Syndrome","Proximal Hamstring Tendinitis","Functional Hip Impingement","Hip Spine Syndrome"],"Video Link":"https://www.youtube.com/watch?v=IbDuqIyxA9w&ab_channel=RehabHero","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/aa6962cd-b634-4c88-b17d-3353393a2094/kettlebell+sumo+deadlift.jpg","URL":"https://www.rehabhero.ca/exercise/kettlebell-sumo-deadlift","Muscle group":["Hip","Lower Back"]}'),
    jsonDecode(
        '{"Title":"POSTERIOR GLIDE ROTATIONS","Directions":"The posterior glide rotations exercise utilizes a light monster band to assist in shoulder centration. Start by looping one end of the band around the front of the shoulder making sure that the band is contacting the humeral aspect of the shoulder joint. Anchor the other end of the band to a stable object behind you. Take a step forward to add tension into the band and raise your arm to 90 degrees shoulder abduction. Begin to rotate the shoulder into end range external rotation and internal rotation while remaining in an abducted position. Complete 15-20 pain free repetitions per set.","Muscles Involved":["glenohumeral joint","glenohumeral joint capsule","rotator cuff","supraspinatus","teres minor","infraspinatus","subscapularis"],"Related Conditions":["dynamic shoulder instability","shoulder impingement","rotator cuff tendinitis","frozen shoulder","adhesive capsulitis"],"Video Link":"https://www.youtube.com/embed/GTylENDw3Sc?feature=oembed","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/651d96d4618c3b3fb434bd12/1696687251013/posterior+glide+rotations.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/posterior-glide-rotations","Muscle group":["Hip"]}')
  ];
  List<dynamic> get HipResults => _HipResults;
  set HipResults(List<dynamic> value) {
    _HipResults = value;
  }

  void addToHipResults(dynamic value) {
    _HipResults.add(value);
  }

  void removeFromHipResults(dynamic value) {
    _HipResults.remove(value);
  }

  void removeAtIndexFromHipResults(int index) {
    _HipResults.removeAt(index);
  }

  void updateHipResultsAtIndex(
    int index,
    dynamic Function(dynamic) updateFn,
  ) {
    _HipResults[index] = updateFn(_HipResults[index]);
  }

  void insertAtIndexInHipResults(int index, dynamic value) {
    _HipResults.insert(index, value);
  }

  List<dynamic> _ShoulderResults = [
    jsonDecode(
        '{"Title":"ECCENTRIC REVERSE FLY","Directions":"This exercise uses a band to strengthen the scapular retractors and shoulder horizontal extensors. Hold a band with your palms facing up and raise them to just below shoulder height. Pull the band apart until the middle of the band touches your chest and slowly return back to starting position at a 5-7 second tempo.","Muscles Involved":["Middle Trapezius","Rhomboids","Rotator Cuff","Posterior Deltoids"],"Related Conditions":["Warm Up","Rhomboid Strain","Upper Cross Syndrome","Rotator Cuff Tear"],"Video Link":"https://www.youtube.com/embed/74wyKVYgETU?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/600c7f6cc9ce5d2dab6275d7/1687709506635/Eccentric%2BReverse%2BFly.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/eccentric-reverse-fly","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"HALF KNEEL ARCHER","Directions":"The half knee archer is a thoracic rotation and shoulder circumduction mobility exercise. Start by kneeling down with one leg and raise both arms out in front of your. Keep one arm stationary forwards and reach directly back with one arm behind you while rotating through the torso. Raise the back arm overhead then forwards while returning back to the starting position.","Muscles Involved":["thoracic spine","scapulothoracic joint","glenohumeral joint","serratus posterior superior","rhomboids","trapezius","multifidus"],"Related Conditions":["costovertebral irritation / costotransverse irritation","Dowager’s hump","Thoracolumbar Syndrome","Cervicothoracic Joint Dysfunction / CT junction dysfunction","Shoulder Impingement","rotator cuff tendinitis","Text Neck","Neck Associated Disorder"],"Video Link":"https://www.youtube.com/watch?v=Xtdvnm9AIXY&t=8s&ab_channel=RehabHero","Image Link":"https://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/646e2acdd3c29100701daaaf/?format=1000w","URL":"https://www.rehabhero.ca/exercise/half-kneel-archer?rq=archer","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"BANDED ARCHERS","Directions":"This exercise is both a mobility and strengthening upper back exercise that targets the thoracic spine and the scapular retractors. For this exercise be sure to keep the pelvis squared forward to help isolate the movement to the upper back and away from the hips.","Muscles Involved":["Rhomboids","Trapezius","Rear Deltoids / Posterior Deltoids","Rotator Cuff","Multifidus","Obliques"],"Related Conditions":["Costovertebral or Costotransverse Joint Irritation","Rotator Cuff Tear","Upper Cross Syndrome","Headaches","Upper Back Pain"],"Video Link":"https://www.youtube.com/embed/vNpTqwhJVag?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/4e925307-6db5-4adb-8339-4d75d5afe674/seated+levator+scapulae+strain.jpg","URL":"https://www.rehabhero.ca/exercise/banded-archers","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"BEAR HUG FLEXION - EXTENSION","Directions":"This is a thoracic mobility exercise that aims to increase flexion and extension range of motion. The bear hug position is used to dissociate scapular motion away from the thoracic spine. This is important for those who tend to end up with shoulder pain as they use their shoulder to compensate for lack of thoracic spine mobility","Muscles Involved":["Trapezius","Erector Spinae","Multifidus"],"Related Conditions":["Upper Back Pain","Headaches","Rotator Cuff Tears","Shoulder Impingement","Frozen Shoulder"],"Video Link":"https://www.youtube.com/embed/N2bAoVYNX4c?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/5fb82e56262d664042dcf38c/1687361817947/Bear%2BHuge%2BFlexion%2BExtension.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/bear-hug-flexion-extension","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"SHOULDER PRESS AND SHRUG","Directions":"This is a modified shoulder press exercise that adds in an end range shrug to recruit the Upper Trapezius muscle. We want to recruit this muscle when it is tight because strengthening a muscle increases a muscle’s tolerance to stretch - helping with decreasing muscle tension. In this instance, we do not want to ‘keep the shoulders down and back’. This exercise is ideally performed with light weights only (<50% 1 RM or RPE).","Muscles Involved":["Upper Trapezius","Deltoids","Rotator Cuff"],"Related Conditions":["Upper Trapezius Strain","Neck Pain","Headaches","Thoracic Outlet Syndrome (TOS)","Brachial Plexopathy","First Rib Dysfunction"],"Video Link":"https://www.youtube.com/embed/5Gr9o9vNI08?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/35d882b2-0346-40ea-9a39-a54ab77e79cd/Towel+Isometric+Neck+Rotation.jpg","URL":"https://www.rehabhero.ca/exercise/shoulder-press-shrug","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"CUFFED ANGELS","Directions":"This exercise is an upper back and shoulder strengthening exercise that will also challenge your shoulder and scapular mobility. Lie down on a yoga mat with your forehead supported by the floor. Place both hands behind your back and lift the elbows towards the ceiling as high as possible. Attempt to maintain this elbow height as you transitions your arms to an overhead press movement.","Muscles Involved":["Scapulothoracic Joint","Glenohumeral Joint","Rhomboids","Trapezius","Rotator Cuff"],"Related Conditions":["Shoulder Impingement","Upper Cross Syndrome","Rotator Cuff Tear","Rotator Cuff Tendinopathy or Tendinitis"],"Video Link":"https://www.youtube.com/embed/0RtxcS9F_Hk?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/0148d01a-0de6-4e6f-8f71-ddd7e1aab703/anterior+glide+rotations.jpg","URL":"https://www.rehabhero.ca/exercise/cuffed-angels","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"UPPER TRAPEZIUS ACTIVE RELEASE","Directions":"This is a self massage technique that uses two massage balls or lacrosse balls. Place both balls on either side of your neck on the muscle belly of the upper trapezius. Keep both arms next to you and then slowly raise them up and overhead to get an active massage of the upper trapezius muscles","Muscles Involved":["Upper Trapezius"],"Related Conditions":["Text Neck","Cervicogenic Headaches","Upper Trapezius Strain","Myofascial Pain Syndrome of Upper Trapezius"],"Video Link":"https://www.youtube.com/embed/OvUxHpEk_PU?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/1646837332370-Y5287B5IWEXBT3WM71UJ/Thoracic%2BFoam%2BRoll.jpg","URL":"https://www.rehabhero.ca/exercise/upper-trapezius-active-release","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"BICEPS CURL & PRESS","Directions":"This is a shoulder and biceps strengthening exercise. You may do this seated or standing. Start by holding two weights in a palms up grip and bend the elbow to raise the weight to roughly shoulder height. Externally rotate the shoulders and press the weight above your head while keeping the elbows directly in line with your wrists. Reverse the motion by lowering the weight and internally rotating the shoulders, then extend the elbow to return to your starting position.","Muscles Involved":["Biceps Brachii","Brachialis","Deltoids","Rotator Cuff","Upper Trapezius"],"Related Conditions":["Strength & Conditioning","Strength Training","Late Stage Recovery Rotator Cuff Tear","Late Stage Recovery Shoulder Impingement","Biceps Tendon Instability","Biceps Tendinopathy","Labral Tear"],"Video Link":"https://www.youtube.com/embed/inCKZLmuvzA?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/605e4bd65c11d47c885eca06/1687727678800/Biceps%2BCurl%2Band%2BPress.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/biceps-curl-and-press","Muscle group":["Shoulder","Elbow"]}'),
    jsonDecode(
        '{"Title":"ELEVATED PUSH UP PLUS","Directions":"This is a scapular protraction stability exercise. Start by taking a high plank stance on an elevated surface such as a bench or sofa. Keep the elbows straight and spine neutral during this exercise. Proceed to retract the shoulder blades all the way and then protract them by pushing them forwards. Be sure to hit max range without flexing or curling the thoracic spine.","Muscles Involved":["Serratus Anterior","Scapulothoracic Joint"],"Related Conditions":["Shoulder Impingement","Rotator Cuff Tear","Posterior Capsule Impingement","Dynamic Shoulder Instability","Labral Tear"],"Video Link":"https://www.youtube.com/embed/CkZ-D7cFR8I?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/606238167a4dc949486c6a20/1687452635782/Elevated%2BScapular%2BPush%2BUp.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/elevated-scapular-push-up","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"BANDED ROBOTS","Directions":"This is an upper back and shoulder strengthening and stability exercise. This exercise may be done standing or seated. If standing loop an exercise band around a stable object like a pole, handrail or squat rack. If seated then loop the band around one foot and squeeze it together with your feet. Pull the band back by squeezing your shoulder blades together. Start with your hands at roughly shoulder height and proceed to raise the arms upwards and overhead. Be sure to keep the elbows stacked directly below the wrists to keep the forearm vertical to the ground.","Muscles Involved":["Trapezius","Posterior Deltoid","Rotator Cuff","Levator Scapulae","Rhomboids"],"Related Conditions":["Shoulder Impingement","Rotator Cuff Tear","Upper Cross Syndrome","Dynamic Shoulder Instability","Posterior Capsule Impingement","AC Joint Sprain"],"Video Link":"https://www.youtube.com/embed/4BZ8QWnIUi4?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/0148d01a-0de6-4e6f-8f71-ddd7e1aab703/anterior+glide+rotations.jpg","URL":"https://www.rehabhero.ca/exercise/pull-back-press","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"TRICEP STRETCH","Directions":"This is a stretch for the triceps muscle group. Raise one arm overhead and bend the elbow so that the hand is placed on your upper back. Use your other arm to pull the elbow closer to your head. Hold the stretch for 3-5 breaths or for up to 20-30 seconds as needed.","Muscles Involved":["Triceps Brachii"],"Related Conditions":["Triceps Tendinitis / Tendinopathy"],"Video Link":"https://www.youtube.com/embed/xuN74WUuXqU?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/608bff6b02786928b17ae2ce/1687359572961/Triceps%2BStretch.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/triceps-stretch","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"STABILITY BALL PEC FLY / CHEST FLY","Directions":"This is a chest strengthening exercise that uses a Swiss ball to increase anti-rotational core demand. Lie down on the ball so that it supports your upper back and neck. Hold two dumbbells at the level of your lower chest and press them upwards until your hands are straight above your shoulders. You may bend the elbows slightly for comfort. Slowly lower your hands towards the floor by spreading them outwards while keeping them in line with your chest horizontally. Raise your hands back up by pulling them together until you return back to starting position.","Muscles Involved":["Pectoralis Major","Pectoralis Minor","Anterior Deltoid","Triceps Brachii"],"Related Conditions":["Strength Training","AC Joint Sprain (Late Stage Recovery)","Pectoralis Strain (Non-acute)"],"Video Link":"https://www.youtube.com/embed/Kb18-snZqOY?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/4ac4eabe-2f36-4f91-a9e1-c8247dcda329/Bottoms+Up+Kettlebell+Decline+Press.jpg","URL":"https://www.rehabhero.ca/exercise/swiss-ball-pec-fly","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"QUADS STRETCH","Directions":"This is a self assisted quadriceps stretch exercise. Start by lying down on your side and grabbing the top ankle with your top hand. Use your hand to bend the knee and push the hips forward to engage in a stretch. Hold for 3-5 breaths or for up to 30 seconds.","Muscles Involved":["Quadriceps"],"Related Conditions":["Runner’s Knee","Jumper’s Knee","Patellofemoral Pain Syndrome","Quadriceps Tendinitis / Patellar Tendinitis","Meniscus Tear","ACL Sprain"],"Video Link":"https://www.youtube.com/embed/xgnCefIx7N8?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/859029da-c82e-4836-aaf0-a865dfcbbcec/step+down+toe+tap.jpg","URL":"https://www.rehabhero.ca/exercise/quadriceps-stretch","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"IRRADIATED SHOULDER PRESS","Directions":"This is a shoulder stability exercise that uses joint irradiation to increase joint centration at the shoulder joint. For this exercise a tennis, lacrosse or massage ball will be required. Squeeze the aforementioned ball with maximum effort and continue to squeeze as you complete an overhead shoulder press motion.","Muscles Involved":["Rotator Cuff"],"Related Conditions":["Shoulder Impingement","Dynamic Shoulder Instability","Posterior Capsule Impingement","Rotator Cuff Tear","Rotator Cuff Tendinitis"],"Video Link":"https://www.youtube.com/embed/lYiDs65Lm64?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/610968acf7516513373195a3/1687709016373/Irradiated%2BShoulder%2BPress.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/irradiated-shoulder-press","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"DRAW THE SWORD","Directions":"This is a rotator cuff strengthening exercise that uses an exercise band to provide multidirectional resistance. Anchor one end of the band down by stepping on it or tying it down to a stable object. Start with the target shoulder’s hand at the opposite hip with the thumb pointed backwards while gripping the band. Simultaneously rotate the hand into a thumbs up position as your pull the band across the body and overhead. This motion should resemble drawing a sword and saluting it overhead.","Muscles Involved":["Rotator Cuff","Lower Trapezius"],"Related Conditions":["Shoulder Impingement","Dynamic Shoulder Instability","Labral Tear","Rotator Cuff Tear / Tendinopathy / Tendinitis","SLAP Lesion","Posterior Capsule Impingement"],"Video Link":"https://www.youtube.com/embed/palYyNDAQU4?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/6109a6e3a94b405864b0ef81/1646597988988/Drawing%2Bthe%2BSword.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/drawing-the-sword","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"TALL PLANK SHOULDER TAP","Directions":"This is a core endurance exercise that focuses on anti-rotation stability. Start in a tall plank position and hold a neutral spine. Place the feet hip distance apart and the hands shoulder distance apart. Without rotating through the torso, lift one hand up to tap the opposite shoulder. Be sure to keep the shoulders and hips squared forward while lifting the hand off of the floor.","Muscles Involved":["Core","Transverse Abdominis","External Oblique","Internal Oblique"],"Related Conditions":["Lower Cross Syndrome","Lumbar Hyperlordosis","Anterior Pelvic Tilt","Functional Scoliosis","Mechanical Low Back Pain","Squat Stability"],"Video Link":"https://www.youtube.com/embed/niAvJrDrxMo?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/4e925307-6db5-4adb-8339-4d75d5afe674/seated+levator+scapulae+strain.jpg","URL":"https://www.rehabhero.ca/exercise/tall-plank-shoulder-tap","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"OVERHEAD TRICEPS EXTENSION","Directions":"This is a strengthening exercise for the triceps brachii muscle group. Hold a weight with both hands and raise the arms overhead. Bend the elbows to lower the weight slowly behind your head and extend it upwards to raise it.","Muscles Involved":["Triceps Brachii"],"Related Conditions":["Strength Training","Olecranon Bursitis","Triceps Tendinitis / Tendinosis / Tendinopathy","Triceps Strain"],"Video Link":"https://www.youtube.com/embed/5Ydq3yZDUKI?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/13843690-1277-4dcc-871f-fee371ef2390/Bottoms+Up+Kettlebell+Incline+Press.jpg","URL":"https://www.rehabhero.ca/exercise/overhead-triceps-extension","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"INTERNAL ROTATION PLATE PERTURBATION","Directions":"This is a stability and proprioception exercise for the shoulder and rotator cuff muscles. Start by anchoring on end of a band to a stable object and loop it through a fractional weight plate. Grip the other end and orient your body so that the hand gripping the band is the one closest to the anchor point. Bend your elbow to 90 degrees elbow flexion. Take a step away from the band’s anchor point to increase the tension in the band (providing internal rotation resistance). Use your free hand to pull on the weight plate and let go to allow it to shake the band. Stabilize the shoulder by resisted the movement generated.","Muscles Involved":["Rotator Cuff","Subscapularis"],"Related Conditions":["Labral Tear","Rotator Cuff Tear","Rotator Cuff Tendinitis / Tendinopathy","Shoulder Impingement","Dynamic Shoulder Instability"],"Video Link":"https://www.youtube.com/embed/ZIPwFufiEHU?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/1b3f4d78-df4f-45c3-8820-229566b136b0/Half+Kneel+Kettlebell+Carry.jpg","URL":"https://www.rehabhero.ca/exercise/internal-rotation-plate-perturbation","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"WALL BALL SHOULDER STARS","Directions":"This is a shoulder stability exercise that aims to build tolerance to overhead movements. Start by placing a Swiss ball against the wall and hold it in place with your arm. From a kneeling tripod position, compress the ball into the wall and move it in a star pattern.","Muscles Involved":["Rotator Cuff","Trapezius","Deltoids","Serratus Anterior"],"Related Conditions":["Dynamic Shoulder Instability","Posterior Capsule Impingement","Biceps Tendinitis / Biceps Tendinopathy","Subacromial Impingement / Shoulder Impingement","Rotator Cuff Tear / Rotator Cuff Tendinitis","Posterior Capsule Impingement","Scapular Winging / Scapular Dyskinesia"],"Video Link":"https://www.youtube.com/embed/OwwIwPJt2so?wmode=opaque","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/9a5621d0-04fe-4bbb-bad6-25674a7bc221/Swiss+Ball+Wall+Circle.jpg","URL":"https://www.rehabhero.ca/exercise/wall-ball-shoulder-stars","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"HALF KNEEL PALLOF PRESS","Directions":"This exercise is used to build anti-rotation stability through the spine. This exercise can be done with a band or cable pulley system. Anchor a band down to the side on a stable object and go into a half kneel position. Hold the band at the middle of your chest while it has some tension. Press your hands forward directly in front of you at roughly chest height and hold for 5-10 seconds or for 3-5 deep breaths. Keep your shoulders stacked directly above the hips and hold a upright neutral spine.","Muscles Involved":["Quadratus Lumborum","Obliques","Core","Multifidus","Lateral Line","Spiral Line"],"Related Conditions":["Idiopathic Scoliosis / Functional Scoliosis","Quadratus Lumborum Strain","Oblique Strain","Chronic Low Back Pain","Sacroiliac Joint Syndrome","Squat Warm Up"],"Video Link":"https://www.youtube.com/embed/-gVgJSDY8is?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/61ab68ea2bb8616334fbcb5e/1646594333300/Half%2BKneel%2BPallof%2BPress.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/half-kneel-pallof-press-1","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"FLOOR CHEST STRETCH | ARM BAR STRETCH","Directions":"This is a stretching exercise for the muscles of the front of the shoulder, arm, and chest. Start by lying down on your stomach with one straight arm stretch out to the side. Slowly use the opposite arm to push the floor to raise one chest off the ground. Go until you feel a light stretch in the targeted muscles. Hold for up to 20-30 seconds and slowly release by lowering the chest back down to the ground.","Muscles Involved":["Anterior Deltoid","Biceps Brachii","Pectoralis Minor","Pectoralis Major","Coracobrachialis","Deep Front Arm Line"],"Related Conditions":["Upper Cross Syndrome","Costochondritis","Shoulder Impingement"],"Video Link":"https://www.youtube.com/embed/7iscKvjmy_g?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/62b60cbe7c89f84893ddea6d/1687709366916/Floor+Chest+Stretch.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/floor-chest-stretch","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"BOTTOMS UP KETTLEBELL FLOOR PRESS","Directions":"This exercise uses a kettlebell to work on shoulder stability. Start by lying down on your back with your knees bent or straight (your preference). Hold a kettlebell in a bottoms up position and complete a FLOOR PRESS motion.","Muscles Involved":["Pectoralis Major","Pectoralis Minor","Anterior Deltoid","Triceps Brachii","Rotator Cuff","Glenohumeral Joint"],"Related Conditions":["AC Joint Sprain (Late Stage Recovery)","Pectoralis Strain (Non-acute)","Shoulder instability","Rotator cuff tear / rotator cuff strain","Rotator cuff tendinitis","Shoulder impingement"],"Video Link":"https://www.youtube.com/embed/co-O3_oex9M?wmode=opaque","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/633773a6c2d2eb44800a1551/1667399457640/Bottoms+Up+Kettlebell+Floor+Press.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/bottoms-up-kettlebell-floor-press","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"SERRATUS WALL SLIDE","Directions":"This exercise is a shoulder stability exercise for the scapular protractors. Have a mini band looped around your hands and elbows against a wall just below shoulder height. Spread the hands to create tension in the band and keep them in line with your elbows and shoulders. Slowly slide your forearms up the wall as high as you can tolerate and slide them back down.","Muscles Involved":["Scapular Protractors:","Serratus Anterior","Pectoralis Major","Pectoralis Minor","Rotator Cuff:","Infraspinatus","Teres Minor"],"Related Conditions":["Shoulder Impingement","Dynamic Shoulder Instability","Labral Tear","Rotator Cuff Tear / Tendinopathy / Tendinitis","SLAP Lesion","Posterior Capsule Impingement"],"Video Link":"https:https://www.youtube.com/embed/7kS0RFd9g0M?feature=oembed","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/63acc0835980506ef63b385f/1672675208610/Serratus+Wall+Slide.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/serratus-wall-slide","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"PLANK SHOULDER CLOCK","Directions":"This is a shoulder stability exercise that uses a loop band to provide resistance. Start by going into a tall plank. Proceed to stretch the band by reaching outwards with your hand in the direction of an hour mark on a clock. Return back to start position and repeat for the other directions.","Muscles Involved":["Serratus Anterior","Rotator Cuff","Trapezius"],"Related Conditions":["Shoulder Impingement","Dynamic Shoulder Instability","Labral Tear","Rotator Cuff Tear / Tendinopathy / Tendinitis","SLAP Lesion","Posterior Capsule Impingement","Winged Scapula / Scapular Winging","Scapular Dyskinesis"],"Video Link":"https:https://www.youtube.com/embed/AC0iacIOE5c?feature=oembed","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/63b603ae7391a5180da4a9d6/1674489637219/Plank+Shoulder+Clock.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/plank-shoulder-clock","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"BANDED ANGELS","Directions":"The banded angels exercise is for building shoulder strength and stability. Start by looping an exercise band around a dumbbell and hold it down with your feet. Pull the band back by squeezing your shoulder blades together into scapular retraction. Raise your arms overhead and be sure to  keep the elbows stacked directly below the wrists to keep the forearm vertical to the ground.","Muscles Involved":["Trapezius","upper trapezius","middle trapezius","lower trapezius","Posterior Deltoid","Rotator Cuff","Levator Scapulae","Rhomboids"],"Related Conditions":["Shoulder Impingement","Rotator Cuff Tear","Upper Cross Syndrome","Dynamic Shoulder Instability","Posterior Capsule Impingement","AC Joint Sprain"],"Video Link":"https://www.youtube.com/embed/BMDqNmHFRPA","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/6446f2b878ce0527efb2d3fe/1687461408876/banded+angels.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/banded-angels","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"DUMBBELL WINDMILL","Directions":"The dumbbell windmill exercise is a compound movement used to improve shoulder, core, and back stability. Start by holding a dumbbell with one hand. Widen up your stance so that your feet are at least shoulder distance apart. Raise the dumbbell straight overhead and lock the arm in a vertical position. Keep about a 25 degree bend in the knees and hinge forwards at the hips. Continue hinging at the hips while rotating the torso so that the arm is vertical to the floor. Run your free hand down the inner aspect of your thigh and leg until you touch the floor. Return to a standing position by reversing the motion to complete a repetition.","Muscles Involved":["core","internal obliques","external obliques","transversus abdominis","erector spinae","quadratus lumborum (QL)","rotator cuff"],"Related Conditions":["sport performance","quadratus lumborum strain","erector spinae strain","oblique strain","glenohumeral labral tear","rotator cuff strain","dynamic shoulder instability"],"Video Link":"https:https://www.youtube.com/embed/BUCD9aHk9nU?feature=oembed","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/645bcb568dd9c9478fea59f8/1684681226940/dumbbell+windmill.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/dumbbell-windmill","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"MODIFIED ECCENTRIC PALLOF PRESS","Directions":"The modified eccentric pallof press exercise is used to strength your core in rotation. Start by anchoring an exercise band to a stable object next to you. Hold the band your navel while there is tension within the band. Proceed to reach forwards with your hands until your arms are straight. Begin to slowly rotate the torso towards the band’s anchor point. Pull the hands back into the body before resetting your position to begin another repetition.","Muscles Involved":["core","internal oblique","external oblique","transversus abdominis","quadratus lumborum","multifidus"],"Related Conditions":["back strain / pulled back","oblique strain","QL strain / quadratus lumborum strain","mechanical low back pain","sacroiliac joint syndrome","lumbar facet syndrome","thoracolumbar syndrome","diastasis recti"],"Video Link":"https://www.youtube.com/embed/89_Mq5XqQLA","Image Link":"http://static1.squarespace.com/static/5f5e8592d2b0854b18af6975/5fb7c850d4788b5df8d8af32/646e46935319dd5e5e4fe116/1686146444130/modified+eccentric+pallof+press.jpg?format=1500w","URL":"https://www.rehabhero.ca/exercise/modified-eccentric-pallof-press","Muscle group":["Shoulder"]}'),
    jsonDecode(
        '{"Title":"SEATED UPPER TRAPEZIUS STRETCH","Directions":"The seated upper trapezius stretch aims to stretch out the neck. Begin by placing a hand on the opposite side of your head. Use your other hand to grip onto the bottom of your seat. Pull your head gently towards the side while rotating the head so that you are looking in the opposite direction. Hold the stretch for 20-30 seconds or as needed for relief.","Muscles Involved":["Upper Trapezius","Splenius Cervicis","Splenius Capitis"],"Related Conditions":["Cervicogenic Headaches","Forward Head Posture","Upper Cross Syndrome","Text Neck / Nerd Neck","Trapezius strain"],"Video Link":"https:https://www.youtube.com/embed/TOioWuL4RxM?feature=oembed","Image Link":"https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/f8af430a-7b2b-41f9-b386-bd828d3e5bcf/Levator+Scapulae+Stretch.jpg","URL":"https://www.rehabhero.ca/exercise/seated-upper-trapezius-stretch","Muscle group":["Shoulder"]}')
  ];
  List<dynamic> get ShoulderResults => _ShoulderResults;
  set ShoulderResults(List<dynamic> value) {
    _ShoulderResults = value;
  }

  void addToShoulderResults(dynamic value) {
    _ShoulderResults.add(value);
  }

  void removeFromShoulderResults(dynamic value) {
    _ShoulderResults.remove(value);
  }

  void removeAtIndexFromShoulderResults(int index) {
    _ShoulderResults.removeAt(index);
  }

  void updateShoulderResultsAtIndex(
    int index,
    dynamic Function(dynamic) updateFn,
  ) {
    _ShoulderResults[index] = updateFn(_ShoulderResults[index]);
  }

  void insertAtIndexInShoulderResults(int index, dynamic value) {
    _ShoulderResults.insert(index, value);
  }

  DateTime? _reminderTime;
  DateTime? get reminderTime => _reminderTime;
  set reminderTime(DateTime? value) {
    _reminderTime = value;
    value != null
        ? prefs.setInt('ff_reminderTime', value.millisecondsSinceEpoch)
        : prefs.remove('ff_reminderTime');
  }
}

LatLng? _latLngFromString(String? val) {
  if (val == null) {
    return null;
  }
  final split = val.split(',');
  final lat = double.parse(split.first);
  final lng = double.parse(split.last);
  return LatLng(lat, lng);
}

void _safeInit(Function() initializeField) {
  try {
    initializeField();
  } catch (_) {}
}

Future _safeInitAsync(Function() initializeField) async {
  try {
    await initializeField();
  } catch (_) {}
}
